services:
  - type: web
    name: django-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn config.wsgi:application
    autoDeploy: true
    envVars:
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        value: "@!_gHn$1oP"  # Замени на реальный секретный ключ
      - key: ALLOWED_HOSTS
        value: "django-render-deploy-3upp.onrender.com"
      - key: DATABASE_URL
        fromDatabase:
          name: django-db  # Название PostgreSQL базы на Render
