# Generated by Django 5.2.5 on 2025-09-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='razdel',
            field=models.TextField(default='obczee'),
        ),
    ]
