# Generated by Django 5.2.5 on 2025-09-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_post_razdel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='razdel',
            field=models.TextField(),
        ),
    ]
