# Generated by Django 5.2.5 on 2025-09-04 22:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_post_razdel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_at', '-date'], 'verbose_name': 'zapis', 'verbose_name_plural': 'zapisi'},
        ),
        migrations.AddField(
            model_name='post',
            name='ai_sentiment',
            field=models.CharField(blank=True, choices=[('позитивное', 'Позитивное'), ('негативное', 'Негативное'), ('нейтральное', 'Нейтральное')], max_length=20, null=True, verbose_name='настроение (ИИ)'),
        ),
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_ai_generated',
            field=models.BooleanField(default=False, verbose_name='создано ИИ'),
        ),
        migrations.AddField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='обновлено'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='post',
            name='razdel',
            field=models.TextField(verbose_name='раздел'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(verbose_name='содержание'),
        ),
    ]
